server:
  port: 8000
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.69.49:3306/fly4j?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:8761/eureka/
  instance:
    ip-address: 101.37.69.49
    hostname: ${eureka.instance.ip-address} # eureka服务显示服务的host
    instance-id: 认证中心-8000
    prefer-ip-address: false # true为自动获取本地IPV4地址
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5

