server:
  port: 9999

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: youlai-auth
          uri: lb://youlai-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
        - id: youlai-file
          uri: lb://youlai-service
          predicates:
            - Path=/api/v1/files/**
          filters:
            - StripPrefix=0
        - id: youlai-admin
          uri: lb://youlai-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: localhost
    hostname: ${eureka.instance.ip-address}
    instance-id: 网关-9999
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5


# 全局参数设置
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 10000
  SocketTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 40000
            # (ribbonReadTimeout + ribbonConnectTimeout) * (maxAutoRetries + 1) * (maxAutoRetriesNextServer + 1);
            # (10000 +10000) * (0 + 1) * (1 + 1)
