@startuml
'https://plantuml.com/sequence-diagram

actor 客户端


客户端 -> TokenEndpoint: 密码模式 \n /oauth/token?gran_type=password
TokenEndpoint -> CompositeTokenGranter: postAccessToken()

CompositeTokenGranter->CompositeTokenGranter: grant( grantType, tokenRequest )

CompositeTokenGranter->ResourceOwnerPasswordTokenGranter: 根据 grant_type 匹配 Granter

ResourceOwnerPasswordTokenGranter-> ResourceOwnerPasswordTokenGranter:getOAuth2Authentication()

ResourceOwnerPasswordTokenGranter-> WebSecurityConfigurerAdapter:this.authenticationManager.authenticate(userAuth)

WebSecurityConfigurerAdapter -> WebSecurityConfigurerAdapter: authenticate()

WebSecurityConfigurerAdapter -> ProviderManager: this.delegate.authenticate()

ProviderManager -> ProviderManager: authenticate()

ProviderManager -> DaoAuthenticationProvider: 匹配支持\nUsernamePasswordAuthenticationToken\n的Provider

DaoAuthenticationProvider -> DaoAuthenticationProvider:authenticate()

ProviderManager <-- DaoAuthenticationProvider: Authentication

WebSecurityConfigurerAdapter <-- ProviderManager: Authentication
ResourceOwnerPasswordTokenGranter <-- WebSecurityConfigurerAdapter: OAuth2Authentication

CompositeTokenGranter <-- ResourceOwnerPasswordTokenGranter: token

TokenEndpoint <-- CompositeTokenGranter:token

客户端 <- TokenEndpoint: token
@enduml