@startuml
'https://plantuml.com/sequence-diagram
actor 客户端

客户端 -> OAuthController: 密码模式 \n /oauth/token?gran_type=password
OAuthController -> TokenEndpoint: postAccessToken()
TokenEndpoint -> CompositeTokenGranter: this.getTokenGranter().grant()
CompositeTokenGranter->CompositeTokenGranter: grant( grantType, tokenRequest )\n根据 grant_type 匹配 Granter
activate  CompositeTokenGranter
CompositeTokenGranter->ResourceOwnerPasswordTokenGranter: getOAuth2Authentication()
deactivate  CompositeTokenGranter
ResourceOwnerPasswordTokenGranter-> WebSecurityConfigurerAdapter:this.authenticationManager.authenticate()
WebSecurityConfigurerAdapter -> ProviderManager: this.delegate.authenticate()
ProviderManager -> ProviderManager: 匹配支持\nUsernamePasswordAuthenticationToken\n的Provider
activate ProviderManager
ProviderManager -> DaoAuthenticationProvider: provider.authenticate(authentication)
deactivate ProviderManager
DaoAuthenticationProvider -> DaoAuthenticationProvider:authenticate()\n用户认证\n密码判读
ProviderManager <-- DaoAuthenticationProvider: Authentication
WebSecurityConfigurerAdapter <-- ProviderManager: Authentication
ResourceOwnerPasswordTokenGranter <-- WebSecurityConfigurerAdapter: OAuth2Authentication
CompositeTokenGranter <-- ResourceOwnerPasswordTokenGranter: OAuth2AccessToken
TokenEndpoint <-- CompositeTokenGranter:OAuth2AccessToken
OAuthController <-- TokenEndpoint:OAuth2AccessToken
客户端 <-- OAuthController: OAuth2AccessToken
@enduml